language: python
python:
- '3.6'
services:
  - postgresql
before_script:
- pip3 install -r requirements.txt
- psql -c 'create database stack;' -U postgres
- python app/config.py
script:
- python -m pytest -v --cov tests --cov-report term-missing
after_success:
- coveralls
deploy:
  provider: heroku
  api_key:
    secure: d540782d-19fd-4b6c-8f9c-b05926832523